#version: '3'
services:
  # nginx:
  #   #platform: linux/amd64
  #   build:
  #     context: .
  #     dockerfile: ./deploy/local/nginx/Dockerfile
  #     args:
  #       - TZ=Asia/Tokyo
  #   depends_on:
  #     - php-fpm
  #   environment:
  #     - TZ=Asia/Tokyo
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./otel-slim-tutrial:/workdir
  #   working_dir: /workdir

  php-fpm:
    #platform: linux/amd64
    build:
      context: .
      dockerfile: ./deploy/local/php/Dockerfile
      args:
        INSTALL_XDEBUG: false
        TZ: Asia/Tokyo
    command: php -S 0.0.0.0:8080 -t public public/index.php
    depends_on:
      - db
    environment:
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_TRACES_EXPORTER=console
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=console
    ports:
      - 8080:8080
    volumes:
      - ./otel-slim-tutrial:/workdir
    working_dir: /workdir

  db:
    build:
      context: .
      dockerfile: ./deploy/local/mysql/Dockerfile
      args:
        - TZ=Asia/Tokyo
    #platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - 13306:3306
    volumes:
      - db-data:/var/lib/mysql

  cache:
    build:
      context: .
      dockerfile: ./deploy/local/redis/Dockerfile
      args:
        - TZ=Asia/Tokyo

volumes:
  db-data:

